default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: voter_media_development
  username: postgres
  password: 123456789
  host: localhost

production:
  <<: *default
  url : <%=ENV["DATABASE_URL"]%>
  database: render_deploy_production
  username: render_deploy
  password: <%=ENV["RENDER_DEPLOY_DATABASE_PASSWORD"]%>
